app:
  message: Message sent to rabbit queue successfully
  
spring:
  activemq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: productexchange
    queue: productqueu
    routingkey: productroutekey
    
server:
  port: 9096
    
