server:
  port: 9006
  rabbitmq:
     addresses: localhost:5672
        rabbitmq:
          exchanges:
            internal: internal.exchange
          queue:
            confirmation: confirmation.queue
          routing-keys:
            internal-confirmation: internal.confirmation.routing-keys
