server:
  port: 9001

spring:
  application:
    name: productMicroservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDB
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}