server:
  port: 9006

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/newDb2?createDatabaseIfNotExist=true&serverTimezone=GMT
    username: root
    password: password

  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect