server:
  port: 9006
spring:
  application:
    name: account-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/accountDB?createDatabaseifNotExists=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    confirmation: confirmation.queue
  routing-keys:
    internal-confirmation: internal.confirmation.routing-key
