server:
  port: 9006
spring:
  application:
    name: account-service
  rabbitmq:
    addresses: rabbitmq:5672
    #addresses: localhost:5672
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/accountDB?autoReconnect=true&useSSL=false
    #url: jdbc:mysql://localhost:3307/accountDB?createDatabaseifNotExists=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

  rabbitmq:
    exchanges:
      internal: internal.exchange
    queue:
      confirmation: confirmation.queue
    routing-keys:
      internal-confirmation: internal.confirmation.routing-key
