server:
  port: 9004

spring:
  application:
    name: OrderService  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/Orders?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql-container:3306/Orders?autoReconnect=true&useSSL=false
    username: root
    #password: bhallas123
    password: password
  rabbitmq:
    #host: localhost
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
# Configure this Discovery Server
eureka:

  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true