server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka
     # defaultZone: http://localhost:8761/eureka
spring:
    application:
      name: email-service
    rabbitmq:
      addresses: rabbitmq:5672
      #addresses: localhost:5672
    mail:
      host: smtp.gmail.com
      port: 587
      username: buyandsellapplication@gmail.com
      password: a2HTZTeH8tbcwfR
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
        protocol: smtp
        test-connection: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    confirmation: confirmation.queue
  routing-keys:
    internal-confirmation: internal.confirmation.routing-key
