server:
  port: 9004

spring:
  application:
    name: OrderService  
  datasource:
    url: jdbc:mysql://localhost:3306/Orders?createDatabaseIfNotExist=true
    username: root
    password: bhallas123
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
# Configure this Discovery Server
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}