
version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    #Remove platform on windows, only used to run mysql on M1 mac
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - my-db:/var/lib/mongoDB
    ports:
      - 27017:27017
    restart: unless-stopped

# Names our volume
volumes:
  my-db:


