app:
  message: Message sent to rabbit queue successfully
  
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: consumerexchange
    queue: consumerqueue
    routingkey: consumerroutekey
    
server:
  port: 9096
