server:
  port: 8999

spring:
  application:
    name: productMicroservice
  data:
    mongodb:
      #host: localhost
      host: mongo-container
      port: 27017
      database: productDB
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://eureka-server-container:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true